### ISSUE TITLE
Correct Language

### ISSUE THREAD

**Issue by richtepa** [richtepa/WebDev#2]
Correct my bad English language : )
(Almost every file)

**Comment by richtepa** [comment]
#3

**Comment by richtepa** [comment]
#5

**Comment by richtepa** [comment]
#4

**Comment by Habilya** [comment]
Can you, please, specify a set of  priority files, you want to be reviewed first?

**Comment by richtepa** [comment]
The most important ones are these in the intents folder and then the actionsongooglesettings.md. At least important is the privacypolicy.html.

**Comment by richtepa** [comment]
#7

**Comment by richtepa** [comment]
#12

**Comment by richtepa** [comment]
I think enough people have checked it. Thank you all!
